### ISSUE TITLE
Remove the need for SuiteSparse_wrapper.c

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/SuiteSparse.jl#11]
I think we can use either Clang.jl or a simple compile time C script to generate all the values in SuiteSparse_wrapper.c and build a .jl file of constants.

Can address https://github.com/JuliaLang/julia/issues/20985 too.

I think we can also then try and bring back simultaneous support for 32 and 64-bit suitesparse.

**Comment by ViralBShah** [comment]
@Gnimuc With your recent PRs, is this something we recently addressed?

**Comment by Gnimuc** [comment]
The last step would be removing `SuiteSparse_wrapper.c` from `SuiteSparse_jll`.

**Comment by ViralBShah** [comment]
Ok - and also from `deps`.

**Comment by ViralBShah** [comment]
Removed the wrapper from the JLL: https://github.com/JuliaPackaging/Yggdrasil/pull/3099

**Comment by nalimilan** [comment]
For the context see https://github.com/JuliaLang/SuiteSparse.jl/pull/2 and https://github.com/JuliaLang/SuiteSparse.jl/pull/3.
