### ISSUE TITLE
Note how to use clang.jl to auto-generate the wrappers in `lib` in the README

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/SuiteSparse.jl#41]
Since it may not be clear to contributors, it is worth noting how to use clang.jl to update the wrappers. Also, it would be nice to note when this needs to happen - perhaps when SuiteSparse versions are bumped.

**Comment by Wimmerer** [comment]
I will include some notes about this once 1.7 is out, since right now it requires 1.7 beta. Perhaps I can figure out how to make CI run the generator every time the `_jll` is bumped, but we'd have to move to that first.

**Comment by ViralBShah** [comment]
We also need to bump SuiteSparse in Julia base for master, and if things work out well, we could even try to get them into the 1.7 backport before RCs are cut.

**Comment by Wimmerer** [comment]
I do not, but happy to learn.

**Comment by ViralBShah** [comment]
Hmm, It seems like @DilumAluthge has some kind of a bot for this: https://github.com/JuliaLang/julia/pull/41166

**Comment by DilumAluthge** [comment]
https://github.com/JuliaLang/BumpStdlibs.jl

**Comment by Wimmerer** [comment]
I'm just a member not a committer so I can't trigger, no reason for me to be one (yet :)) anyway.
