### ISSUE TITLE
`_I64_MAX` missing on Windows

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/SuiteSparse.jl#6]
Trying to merge the new changes back into JuliaLang/Julia, one error is on Windows when the package is loaded https://build.julialang.org/#/builders/37/builds/3820.

The problem seems to be this line:

https://github.com/JuliaLang/SuiteSparse.jl/blob/770b8de706773737720c3e1ba8829f2a64663133/lib/x86_64-w64-mingw32.jl#L2091

and that `_I64_MAX` is undefined. Should the generator have added it to https://github.com/JuliaLang/SuiteSparse.jl/blob/770b8de706773737720c3e1ba8829f2a64663133/src/LibSuiteSparse.jl#L10?

cc @Gnimuc

**Comment by Gnimuc** [comment]
Yeah, it should be added. But I'm wondering why the CI in this repo didn't catch this error.

**Comment by Gnimuc** [comment]
Oops! The CI did catch the error in the build phase: https://github.com/JuliaLang/SuiteSparse.jl/runs/2602018561#step:5:55

**Comment by KristofferC** [comment]
Hm, that should probably have failed the build.

**Comment by ViralBShah** [comment]
Some related discussion around this: https://github.com/JuliaLang/julia/issues/37322

Anyways, it is not relevant, and the fix in #8 is a better solution.
